<?php

namespace ContainerG9Eej1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCloudConnectionServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'cloud_connection_service' shared autowired service.
     *
     * @return \App\Services\CloudConnectionService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['cloud_connection_service'] = new \App\Services\CloudConnectionService(($container->privates['App\\Services\\ConfigService'] ?? ($container->privates['App\\Services\\ConfigService'] = new \App\Services\ConfigService(($container->services['kernel'] ?? $container->get('kernel', 1))))), ($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
