<?php

namespace ContainerG9Eej1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCloudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\CloudController' shared autowired service.
     *
     * @return \App\CloudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['kernel'] ?? $container->get('kernel', 1));
        $b = ($container->privates['App\\Services\\ConfigService'] ?? ($container->privates['App\\Services\\ConfigService'] = new \App\Services\ConfigService($a)));

        $container->services['App\\CloudController'] = $instance = new \App\CloudController($a, $b, new \App\Services\CloudConnectionService($b, $a));

        $instance->setContainer(($container->privates['.service_locator.Ejq_DCG'] ?? $container->load('get_ServiceLocator_EjqDCGService'))->withContext('App\\CloudController', $container));

        return $instance;
    }
}
