<?php

namespace ContainerG9Eej1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProxyControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\ProxyController' shared autowired service.
     *
     * @return \App\ProxyController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Services\\ConfigService'] ?? ($container->privates['App\\Services\\ConfigService'] = new \App\Services\ConfigService(($container->services['kernel'] ?? $container->get('kernel', 1)))));

        $container->services['App\\ProxyController'] = $instance = new \App\ProxyController(new \App\Services\ParserService(($container->services['kernel'] ?? $container->get('kernel', 1)), $a, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))), $a, ($container->services['http_cache'] ?? $container->getHttpCacheService()));

        $instance->setContainer(($container->privates['.service_locator.Ejq_DCG'] ?? $container->load('get_ServiceLocator_EjqDCGService'))->withContext('App\\ProxyController', $container));

        return $instance;
    }
}
