<?php

namespace ContainerG9Eej1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PublicController' shared autowired service.
     *
     * @return \App\Controller\PublicController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\PublicController'] = new \App\Controller\PublicController(($container->privates['App\\Services\\UserService'] ?? $container->load('getUserServiceService')));
    }
}
