<?php

namespace ContainerG9Eej1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Services\UserService' shared autowired service.
     *
     * @return \App\Services\UserService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Services\\UserService'] = new \App\Services\UserService(new \App\Services\DatabaseService(($container->privates['App\\Services\\ConfigService'] ?? ($container->privates['App\\Services\\ConfigService'] = new \App\Services\ConfigService(($container->services['kernel'] ?? $container->get('kernel', 1)))))));
    }
}
