<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKXxYWxP\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKXxYWxP/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKXxYWxP.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKXxYWxP\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKXxYWxP\App_KernelProdContainer([
    'container.build_hash' => 'KXxYWxP',
    'container.build_id' => 'b7af5a4f',
    'container.build_time' => 1758634292,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKXxYWxP');
