<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG9Eej1f\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG9Eej1f/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerG9Eej1f.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerG9Eej1f\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerG9Eej1f\App_KernelProdContainer([
    'container.build_hash' => 'G9Eej1f',
    'container.build_id' => '4e2a0201',
    'container.build_time' => 1777045525,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG9Eej1f');
