services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
    public: true

  App\:
    resource: '../src/*'
    exclude: '../src/{Controller,DependencyInjection,Entity,Migrations,Tests,Kernel.development}'

  App\CacheKernel:
    decorates: http_cache
    arguments:
      - '@kernel'
      - '@http_cache.store'
      - '@?esi'

  cloud_connection_service:
    class: App\Services\CloudConnectionService
    public: true